#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          1
bspc config window_gap           12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=tiled follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a gnome-pomodoro state=floating
picom

bspc config normal_border_color "#4c566a"
bspc config active_border_color "#3b4252"
bspc config focused_border_color "#a3be8c"
bspc config presel_feedback_color "#ebcb8b"

