#!/bin/zsh

# terminal emulator
super + Return
	st

# terminal emulator
super + shift + Return
	urxvt

# program launcher
super + @space 
	dmenu_run

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# Custom startup keys
#

# accents (personal script)
super + g
	d-char

# workspaces loader (personal script)
super + x
	d-workspaces

# edit config files script (personal script)
super + c
	d-config

# power dmenu script (personal script)
super + v
	d-lockmenu

# browser bookmarks (personal script)
super + b
	d-web

# browser
super + shift + b
	firefox

# cli file manager
super + n
	st -e /usr/bin/ranger

# bluetooth
super + m
	blueberry

# gui file manager
super + shift + n
	nemo

# libreoffice writer
super + shift + o
	gtk-pipe-viewer

# email client (personal script)
super + a
	st -e SM.sh

# email addresses (personal script)
super + shift + a
	d-email

# screenshot
super + shift + s
	gnome-screenshot

# anki
super + e
	anki --no-sandbox
