#!/bin/zsh

# terminal emulator
super + Return
	st

# program launcher
super + @space 
	dmenu_run

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# Custom startup keys
#

# accents
super + g
	d-char

# workspaces loader
super + x
	d-workspaces

# edit config files script
super + c
	d-config

# power dmenu script
super + v
	d-lockmenu

# browser bookmarks
super + b
	d-web

# browser
super + shift + b
	firefox

# cli file manager
super + n
	st -e /usr/bin/ranger

# bluetooth
super + m
	blueberry

# gui file manager
super + shift + n
	nemo

# email client
super + a
	st -e SM.sh

# email addresses
super + shift + a
	d-email

# screenshot
super + shift + s
	gnome-screenshot

# anki
super + e
	anki --no-sandbox

# pass
super + shift + p
	passmenu
